[[redirects]]
  from = "https://otwartaturystyka.netlify.app/*"
  to = "https://otwartaturystyka.pl/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://otwartaturystyka.pl/regions/rudnik/*"
  to = "https://otwartaturystyka.pl/pobierz"
  status = 301
  force = true
